# The image will be at ghcr.io/yourusername/name
name: mblue

base-container: ghcr.io/ublue-os/silverblue-main

fedora-version: 37

description: Menno's custom ublue

rpms:
  - python3-pip # needed for yafti (the first boot installer)
  - powertop

flatpaks:
  - org.mozilla.firefox
  - com.mattjakeman.ExtensionManager
  - org.libreoffice.LibreOffice
  - org.gustavoperedo.FontDownloader
  - com.github.tchx84.Flatseal
  - io.github.celluloid_player.Celluloid
